language: go
install:
  - cd -
  - go get github.com/gorilla/mux
  - go get github.com/howeyc/fsnotify
  - go install mysite
  - go install site
  - go install storage
  - go install resty
  - go build src/dcms.go